### ISSUE TITLE
Icon list on blazor documentation is broken

### ISSUE THREAD

**Issue by mmamfgm** [telerik/blazor-docs#701] opened 2022-01-14 21:44 UTC
On [this site](https://docs.telerik.com/blazor-ui/common-features/font-icons#icons-list) I get the following message: 

![image](https://user-images.githubusercontent.com/28861327/149589240-73ed6ab3-91b2-43d6-9bc4-c721c89058f8.png)

**Comment by marin-bratanov** [comment] 2022-01-15 14:49
Thank you for bringing this up @mmamfgm 
I will close this as a duplicate of the first one I noticed where I added some comments with things to try if the issue persists https://github.com/telerik/blazor-docs/issues/702
Let's keep further info in that thread.
Looking forward to your feedback!

**Closed by marin-bratanov** 2022-01-15 14:49 UTC
